language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("Reproducible")); Pkg.add("Plots"); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'include("example/make.jl")'

# use examples/docs to produce gh-pages website
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: example/build
  on:
    branch: master